// Single shared browser client (generated by the Cloud integration).
// Re-exported here so every part of the app uses the same session storage.
export { supabase } from "@/integrations/supabase/client";
