/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAccreditationRouteImport } from './routes/admin/accreditation'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminApplicationsRouteImport } from './routes/admin/applications'
import { Route as AdminAttendanceRouteImport } from './routes/admin/attendance'
import { Route as AdminCertificatesRouteImport } from './routes/admin/certificates'
import { Route as AdminCommitteesRouteImport } from './routes/admin/committees'
import { Route as AdminHoursRouteImport } from './routes/admin/hours'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'
import { Route as AdminShiftsRouteImport } from './routes/admin/shifts'
import { Route as AdminTrainingRouteImport } from './routes/admin/training'
import { Route as VolunteerAccreditationRouteImport } from './routes/volunteer/accreditation'
import { Route as VolunteerAchievementsRouteImport } from './routes/volunteer/achievements'
import { Route as VolunteerApplicationsRouteImport } from './routes/volunteer/applications'
import { Route as VolunteerAttendanceRouteImport } from './routes/volunteer/attendance'
import { Route as VolunteerCertificatesRouteImport } from './routes/volunteer/certificates'
import { Route as VolunteerDashboardRouteImport } from './routes/volunteer/dashboard'
import { Route as VolunteerHoursRouteImport } from './routes/volunteer/hours'
import { Route as VolunteerMyEventsRouteImport } from './routes/volunteer/my-events'
import { Route as VolunteerNotificationsRouteImport } from './routes/volunteer/notifications'
import { Route as VolunteerProfileRouteImport } from './routes/volunteer/profile'
import { Route as VolunteerScheduleRouteImport } from './routes/volunteer/schedule'
import { Route as VolunteerTrainingRouteImport } from './routes/volunteer/training'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AdminEventsIndexRouteImport } from './routes/admin/events/index'
import { Route as AdminEventsEventIdRouteImport } from './routes/admin/events/$eventId'
import { Route as AdminEventsCreateRouteImport } from './routes/admin/events/create'
import { Route as AdminVolunteersIndexRouteImport } from './routes/admin/volunteers/index'
import { Route as AdminVolunteersVolunteerIdRouteImport } from './routes/admin/volunteers/$volunteerId'
import { Route as VolunteerCertificatesCertificateIdRouteImport } from './routes/volunteer/certificates/$certificateId'
import { Route as VolunteerEventsIndexRouteImport } from './routes/volunteer/events/index'
import { Route as VolunteerEventsEventIdRouteImport } from './routes/volunteer/events/$eventId'
import { Route as VolunteerTrainingTrainingIdRouteImport } from './routes/volunteer/training/$trainingId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccreditationRoute = AdminAccreditationRouteImport.update({
  id: '/accreditation',
  path: '/accreditation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCertificatesRoute = AdminCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommitteesRoute = AdminCommitteesRouteImport.update({
  id: '/committees',
  path: '/committees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHoursRoute = AdminHoursRouteImport.update({
  id: '/hours',
  path: '/hours',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShiftsRoute = AdminShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrainingRoute = AdminTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AdminRoute,
} as any)
const VolunteerAccreditationRoute = VolunteerAccreditationRouteImport.update({
  id: '/volunteer/accreditation',
  path: '/volunteer/accreditation',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerAchievementsRoute = VolunteerAchievementsRouteImport.update({
  id: '/volunteer/achievements',
  path: '/volunteer/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerApplicationsRoute = VolunteerApplicationsRouteImport.update({
  id: '/volunteer/applications',
  path: '/volunteer/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerAttendanceRoute = VolunteerAttendanceRouteImport.update({
  id: '/volunteer/attendance',
  path: '/volunteer/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerCertificatesRoute = VolunteerCertificatesRouteImport.update({
  id: '/volunteer/certificates',
  path: '/volunteer/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerDashboardRoute = VolunteerDashboardRouteImport.update({
  id: '/volunteer/dashboard',
  path: '/volunteer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerHoursRoute = VolunteerHoursRouteImport.update({
  id: '/volunteer/hours',
  path: '/volunteer/hours',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerMyEventsRoute = VolunteerMyEventsRouteImport.update({
  id: '/volunteer/my-events',
  path: '/volunteer/my-events',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerNotificationsRoute = VolunteerNotificationsRouteImport.update({
  id: '/volunteer/notifications',
  path: '/volunteer/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerProfileRoute = VolunteerProfileRouteImport.update({
  id: '/volunteer/profile',
  path: '/volunteer/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerScheduleRoute = VolunteerScheduleRouteImport.update({
  id: '/volunteer/schedule',
  path: '/volunteer/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerTrainingRoute = VolunteerTrainingRouteImport.update({
  id: '/volunteer/training',
  path: '/volunteer/training',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsEventIdRoute = AdminEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsCreateRoute = AdminEventsCreateRouteImport.update({
  id: '/events/create',
  path: '/events/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVolunteersIndexRoute = AdminVolunteersIndexRouteImport.update({
  id: '/volunteers/',
  path: '/volunteers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVolunteersVolunteerIdRoute =
  AdminVolunteersVolunteerIdRouteImport.update({
    id: '/volunteers/$volunteerId',
    path: '/volunteers/$volunteerId',
    getParentRoute: () => AdminRoute,
  } as any)
const VolunteerCertificatesCertificateIdRoute =
  VolunteerCertificatesCertificateIdRouteImport.update({
    id: '/$certificateId',
    path: '/$certificateId',
    getParentRoute: () => VolunteerCertificatesRoute,
  } as any)
const VolunteerEventsIndexRoute = VolunteerEventsIndexRouteImport.update({
  id: '/volunteer/events/',
  path: '/volunteer/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerEventsEventIdRoute = VolunteerEventsEventIdRouteImport.update({
  id: '/volunteer/events/$eventId',
  path: '/volunteer/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerTrainingTrainingIdRoute =
  VolunteerTrainingTrainingIdRouteImport.update({
    id: '/$trainingId',
    path: '/$trainingId',
    getParentRoute: () => VolunteerTrainingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/accreditation': typeof AdminAccreditationRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/committees': typeof AdminCommitteesRoute
  '/admin/hours': typeof AdminHoursRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/shifts': typeof AdminShiftsRoute
  '/admin/training': typeof AdminTrainingRoute
  '/volunteer/accreditation': typeof VolunteerAccreditationRoute
  '/volunteer/achievements': typeof VolunteerAchievementsRoute
  '/volunteer/applications': typeof VolunteerApplicationsRoute
  '/volunteer/attendance': typeof VolunteerAttendanceRoute
  '/volunteer/certificates': typeof VolunteerCertificatesRouteWithChildren
  '/volunteer/dashboard': typeof VolunteerDashboardRoute
  '/volunteer/hours': typeof VolunteerHoursRoute
  '/volunteer/my-events': typeof VolunteerMyEventsRoute
  '/volunteer/notifications': typeof VolunteerNotificationsRoute
  '/volunteer/profile': typeof VolunteerProfileRoute
  '/volunteer/schedule': typeof VolunteerScheduleRoute
  '/volunteer/training': typeof VolunteerTrainingRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdRoute
  '/admin/events/create': typeof AdminEventsCreateRoute
  '/admin/volunteers/$volunteerId': typeof AdminVolunteersVolunteerIdRoute
  '/volunteer/certificates/$certificateId': typeof VolunteerCertificatesCertificateIdRoute
  '/volunteer/events/$eventId': typeof VolunteerEventsEventIdRoute
  '/volunteer/training/$trainingId': typeof VolunteerTrainingTrainingIdRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/volunteers/': typeof AdminVolunteersIndexRoute
  '/volunteer/events/': typeof VolunteerEventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/accreditation': typeof AdminAccreditationRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/committees': typeof AdminCommitteesRoute
  '/admin/hours': typeof AdminHoursRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/shifts': typeof AdminShiftsRoute
  '/admin/training': typeof AdminTrainingRoute
  '/volunteer/accreditation': typeof VolunteerAccreditationRoute
  '/volunteer/achievements': typeof VolunteerAchievementsRoute
  '/volunteer/applications': typeof VolunteerApplicationsRoute
  '/volunteer/attendance': typeof VolunteerAttendanceRoute
  '/volunteer/certificates': typeof VolunteerCertificatesRouteWithChildren
  '/volunteer/dashboard': typeof VolunteerDashboardRoute
  '/volunteer/hours': typeof VolunteerHoursRoute
  '/volunteer/my-events': typeof VolunteerMyEventsRoute
  '/volunteer/notifications': typeof VolunteerNotificationsRoute
  '/volunteer/profile': typeof VolunteerProfileRoute
  '/volunteer/schedule': typeof VolunteerScheduleRoute
  '/volunteer/training': typeof VolunteerTrainingRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdRoute
  '/admin/events/create': typeof AdminEventsCreateRoute
  '/admin/volunteers/$volunteerId': typeof AdminVolunteersVolunteerIdRoute
  '/volunteer/certificates/$certificateId': typeof VolunteerCertificatesCertificateIdRoute
  '/volunteer/events/$eventId': typeof VolunteerEventsEventIdRoute
  '/volunteer/training/$trainingId': typeof VolunteerTrainingTrainingIdRoute
  '/admin/events': typeof AdminEventsIndexRoute
  '/admin/volunteers': typeof AdminVolunteersIndexRoute
  '/volunteer/events': typeof VolunteerEventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/accreditation': typeof AdminAccreditationRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/committees': typeof AdminCommitteesRoute
  '/admin/hours': typeof AdminHoursRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/shifts': typeof AdminShiftsRoute
  '/admin/training': typeof AdminTrainingRoute
  '/volunteer/accreditation': typeof VolunteerAccreditationRoute
  '/volunteer/achievements': typeof VolunteerAchievementsRoute
  '/volunteer/applications': typeof VolunteerApplicationsRoute
  '/volunteer/attendance': typeof VolunteerAttendanceRoute
  '/volunteer/certificates': typeof VolunteerCertificatesRouteWithChildren
  '/volunteer/dashboard': typeof VolunteerDashboardRoute
  '/volunteer/hours': typeof VolunteerHoursRoute
  '/volunteer/my-events': typeof VolunteerMyEventsRoute
  '/volunteer/notifications': typeof VolunteerNotificationsRoute
  '/volunteer/profile': typeof VolunteerProfileRoute
  '/volunteer/schedule': typeof VolunteerScheduleRoute
  '/volunteer/training': typeof VolunteerTrainingRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdRoute
  '/admin/events/create': typeof AdminEventsCreateRoute
  '/admin/volunteers/$volunteerId': typeof AdminVolunteersVolunteerIdRoute
  '/volunteer/certificates/$certificateId': typeof VolunteerCertificatesCertificateIdRoute
  '/volunteer/events/$eventId': typeof VolunteerEventsEventIdRoute
  '/volunteer/training/$trainingId': typeof VolunteerTrainingTrainingIdRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/volunteers/': typeof AdminVolunteersIndexRoute
  '/volunteer/events/': typeof VolunteerEventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/about'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/mcp'
    | '/register'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/accreditation'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/attendance'
    | '/admin/certificates'
    | '/admin/committees'
    | '/admin/hours'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/shifts'
    | '/admin/training'
    | '/volunteer/accreditation'
    | '/volunteer/achievements'
    | '/volunteer/applications'
    | '/volunteer/attendance'
    | '/volunteer/certificates'
    | '/volunteer/dashboard'
    | '/volunteer/hours'
    | '/volunteer/my-events'
    | '/volunteer/notifications'
    | '/volunteer/profile'
    | '/volunteer/schedule'
    | '/volunteer/training'
    | '/admin/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/events/$eventId'
    | '/admin/events/create'
    | '/admin/volunteers/$volunteerId'
    | '/volunteer/certificates/$certificateId'
    | '/volunteer/events/$eventId'
    | '/volunteer/training/$trainingId'
    | '/admin/events/'
    | '/admin/volunteers/'
    | '/volunteer/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/mcp'
    | '/register'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/accreditation'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/attendance'
    | '/admin/certificates'
    | '/admin/committees'
    | '/admin/hours'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/shifts'
    | '/admin/training'
    | '/volunteer/accreditation'
    | '/volunteer/achievements'
    | '/volunteer/applications'
    | '/volunteer/attendance'
    | '/volunteer/certificates'
    | '/volunteer/dashboard'
    | '/volunteer/hours'
    | '/volunteer/my-events'
    | '/volunteer/notifications'
    | '/volunteer/profile'
    | '/volunteer/schedule'
    | '/volunteer/training'
    | '/admin'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/events/$eventId'
    | '/admin/events/create'
    | '/admin/volunteers/$volunteerId'
    | '/volunteer/certificates/$certificateId'
    | '/volunteer/events/$eventId'
    | '/volunteer/training/$trainingId'
    | '/admin/events'
    | '/admin/volunteers'
    | '/volunteer/events'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/about'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/mcp'
    | '/register'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/accreditation'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/attendance'
    | '/admin/certificates'
    | '/admin/committees'
    | '/admin/hours'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/shifts'
    | '/admin/training'
    | '/volunteer/accreditation'
    | '/volunteer/achievements'
    | '/volunteer/applications'
    | '/volunteer/attendance'
    | '/volunteer/certificates'
    | '/volunteer/dashboard'
    | '/volunteer/hours'
    | '/volunteer/my-events'
    | '/volunteer/notifications'
    | '/volunteer/profile'
    | '/volunteer/schedule'
    | '/volunteer/training'
    | '/admin/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/events/$eventId'
    | '/admin/events/create'
    | '/admin/volunteers/$volunteerId'
    | '/volunteer/certificates/$certificateId'
    | '/volunteer/events/$eventId'
    | '/volunteer/training/$trainingId'
    | '/admin/events/'
    | '/admin/volunteers/'
    | '/volunteer/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  VolunteerAccreditationRoute: typeof VolunteerAccreditationRoute
  VolunteerAchievementsRoute: typeof VolunteerAchievementsRoute
  VolunteerApplicationsRoute: typeof VolunteerApplicationsRoute
  VolunteerAttendanceRoute: typeof VolunteerAttendanceRoute
  VolunteerCertificatesRoute: typeof VolunteerCertificatesRouteWithChildren
  VolunteerDashboardRoute: typeof VolunteerDashboardRoute
  VolunteerHoursRoute: typeof VolunteerHoursRoute
  VolunteerMyEventsRoute: typeof VolunteerMyEventsRoute
  VolunteerNotificationsRoute: typeof VolunteerNotificationsRoute
  VolunteerProfileRoute: typeof VolunteerProfileRoute
  VolunteerScheduleRoute: typeof VolunteerScheduleRoute
  VolunteerTrainingRoute: typeof VolunteerTrainingRouteWithChildren
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  VolunteerEventsEventIdRoute: typeof VolunteerEventsEventIdRoute
  VolunteerEventsIndexRoute: typeof VolunteerEventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/accreditation': {
      id: '/admin/accreditation'
      path: '/accreditation'
      fullPath: '/admin/accreditation'
      preLoaderRoute: typeof AdminAccreditationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/certificates': {
      id: '/admin/certificates'
      path: '/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AdminCertificatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/committees': {
      id: '/admin/committees'
      path: '/committees'
      fullPath: '/admin/committees'
      preLoaderRoute: typeof AdminCommitteesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hours': {
      id: '/admin/hours'
      path: '/hours'
      fullPath: '/admin/hours'
      preLoaderRoute: typeof AdminHoursRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shifts': {
      id: '/admin/shifts'
      path: '/shifts'
      fullPath: '/admin/shifts'
      preLoaderRoute: typeof AdminShiftsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/training': {
      id: '/admin/training'
      path: '/training'
      fullPath: '/admin/training'
      preLoaderRoute: typeof AdminTrainingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/volunteer/accreditation': {
      id: '/volunteer/accreditation'
      path: '/volunteer/accreditation'
      fullPath: '/volunteer/accreditation'
      preLoaderRoute: typeof VolunteerAccreditationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/achievements': {
      id: '/volunteer/achievements'
      path: '/volunteer/achievements'
      fullPath: '/volunteer/achievements'
      preLoaderRoute: typeof VolunteerAchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/applications': {
      id: '/volunteer/applications'
      path: '/volunteer/applications'
      fullPath: '/volunteer/applications'
      preLoaderRoute: typeof VolunteerApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/attendance': {
      id: '/volunteer/attendance'
      path: '/volunteer/attendance'
      fullPath: '/volunteer/attendance'
      preLoaderRoute: typeof VolunteerAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/certificates': {
      id: '/volunteer/certificates'
      path: '/volunteer/certificates'
      fullPath: '/volunteer/certificates'
      preLoaderRoute: typeof VolunteerCertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/dashboard': {
      id: '/volunteer/dashboard'
      path: '/volunteer/dashboard'
      fullPath: '/volunteer/dashboard'
      preLoaderRoute: typeof VolunteerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/hours': {
      id: '/volunteer/hours'
      path: '/volunteer/hours'
      fullPath: '/volunteer/hours'
      preLoaderRoute: typeof VolunteerHoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/my-events': {
      id: '/volunteer/my-events'
      path: '/volunteer/my-events'
      fullPath: '/volunteer/my-events'
      preLoaderRoute: typeof VolunteerMyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/notifications': {
      id: '/volunteer/notifications'
      path: '/volunteer/notifications'
      fullPath: '/volunteer/notifications'
      preLoaderRoute: typeof VolunteerNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/profile': {
      id: '/volunteer/profile'
      path: '/volunteer/profile'
      fullPath: '/volunteer/profile'
      preLoaderRoute: typeof VolunteerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/schedule': {
      id: '/volunteer/schedule'
      path: '/volunteer/schedule'
      fullPath: '/volunteer/schedule'
      preLoaderRoute: typeof VolunteerScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/training': {
      id: '/volunteer/training'
      path: '/volunteer/training'
      fullPath: '/volunteer/training'
      preLoaderRoute: typeof VolunteerTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/': {
      id: '/admin/events/'
      path: '/events'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/$eventId': {
      id: '/admin/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/admin/events/$eventId'
      preLoaderRoute: typeof AdminEventsEventIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/create': {
      id: '/admin/events/create'
      path: '/events/create'
      fullPath: '/admin/events/create'
      preLoaderRoute: typeof AdminEventsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/volunteers/': {
      id: '/admin/volunteers/'
      path: '/volunteers'
      fullPath: '/admin/volunteers/'
      preLoaderRoute: typeof AdminVolunteersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/volunteers/$volunteerId': {
      id: '/admin/volunteers/$volunteerId'
      path: '/volunteers/$volunteerId'
      fullPath: '/admin/volunteers/$volunteerId'
      preLoaderRoute: typeof AdminVolunteersVolunteerIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/volunteer/certificates/$certificateId': {
      id: '/volunteer/certificates/$certificateId'
      path: '/$certificateId'
      fullPath: '/volunteer/certificates/$certificateId'
      preLoaderRoute: typeof VolunteerCertificatesCertificateIdRouteImport
      parentRoute: typeof VolunteerCertificatesRoute
    }
    '/volunteer/events/': {
      id: '/volunteer/events/'
      path: '/volunteer/events'
      fullPath: '/volunteer/events/'
      preLoaderRoute: typeof VolunteerEventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/events/$eventId': {
      id: '/volunteer/events/$eventId'
      path: '/volunteer/events/$eventId'
      fullPath: '/volunteer/events/$eventId'
      preLoaderRoute: typeof VolunteerEventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/training/$trainingId': {
      id: '/volunteer/training/$trainingId'
      path: '/$trainingId'
      fullPath: '/volunteer/training/$trainingId'
      preLoaderRoute: typeof VolunteerTrainingTrainingIdRouteImport
      parentRoute: typeof VolunteerTrainingRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAccreditationRoute: typeof AdminAccreditationRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminCertificatesRoute: typeof AdminCertificatesRoute
  AdminCommitteesRoute: typeof AdminCommitteesRoute
  AdminHoursRoute: typeof AdminHoursRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminShiftsRoute: typeof AdminShiftsRoute
  AdminTrainingRoute: typeof AdminTrainingRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEventsEventIdRoute: typeof AdminEventsEventIdRoute
  AdminEventsCreateRoute: typeof AdminEventsCreateRoute
  AdminVolunteersVolunteerIdRoute: typeof AdminVolunteersVolunteerIdRoute
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
  AdminVolunteersIndexRoute: typeof AdminVolunteersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccreditationRoute: AdminAccreditationRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminCertificatesRoute: AdminCertificatesRoute,
  AdminCommitteesRoute: AdminCommitteesRoute,
  AdminHoursRoute: AdminHoursRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminShiftsRoute: AdminShiftsRoute,
  AdminTrainingRoute: AdminTrainingRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEventsEventIdRoute: AdminEventsEventIdRoute,
  AdminEventsCreateRoute: AdminEventsCreateRoute,
  AdminVolunteersVolunteerIdRoute: AdminVolunteersVolunteerIdRoute,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
  AdminVolunteersIndexRoute: AdminVolunteersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface VolunteerCertificatesRouteChildren {
  VolunteerCertificatesCertificateIdRoute: typeof VolunteerCertificatesCertificateIdRoute
}

const VolunteerCertificatesRouteChildren: VolunteerCertificatesRouteChildren = {
  VolunteerCertificatesCertificateIdRoute:
    VolunteerCertificatesCertificateIdRoute,
}

const VolunteerCertificatesRouteWithChildren =
  VolunteerCertificatesRoute._addFileChildren(
    VolunteerCertificatesRouteChildren,
  )

interface VolunteerTrainingRouteChildren {
  VolunteerTrainingTrainingIdRoute: typeof VolunteerTrainingTrainingIdRoute
}

const VolunteerTrainingRouteChildren: VolunteerTrainingRouteChildren = {
  VolunteerTrainingTrainingIdRoute: VolunteerTrainingTrainingIdRoute,
}

const VolunteerTrainingRouteWithChildren =
  VolunteerTrainingRoute._addFileChildren(VolunteerTrainingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  VolunteerAccreditationRoute: VolunteerAccreditationRoute,
  VolunteerAchievementsRoute: VolunteerAchievementsRoute,
  VolunteerApplicationsRoute: VolunteerApplicationsRoute,
  VolunteerAttendanceRoute: VolunteerAttendanceRoute,
  VolunteerCertificatesRoute: VolunteerCertificatesRouteWithChildren,
  VolunteerDashboardRoute: VolunteerDashboardRoute,
  VolunteerHoursRoute: VolunteerHoursRoute,
  VolunteerMyEventsRoute: VolunteerMyEventsRoute,
  VolunteerNotificationsRoute: VolunteerNotificationsRoute,
  VolunteerProfileRoute: VolunteerProfileRoute,
  VolunteerScheduleRoute: VolunteerScheduleRoute,
  VolunteerTrainingRoute: VolunteerTrainingRouteWithChildren,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  VolunteerEventsEventIdRoute: VolunteerEventsEventIdRoute,
  VolunteerEventsIndexRoute: VolunteerEventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
